services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_memory
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - rag_net
  chromadb:
    build:
      context: ./src/chromadb
      dockerfile: Dockerfile
    container_name: chromadb
    ports:
      - "8020:8020"
    environment:
      - CHROMADB_PERSIST_DIRECTORY=/app/chroma_db_data
    volumes:
      - ./data/chromadb:/app/chroma_db_data
    networks:
      - rag_net
  llama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: llama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama
      - ./start_ollama.sh:/start.sh
    entrypoint: ["/bin/sh", "/start.sh"]
    networks:
      - rag_net

  fastapi:
    build:
      context: ./src/fastapi
      dockerfile: Dockerfile.fastapi
    ports:
      - "9020:9020"
    env_file:
      - .env
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_API_KEY}
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - DATABASE_URL=postgresql://user:password@postgres:5432/rag_memory
      - HF_HOME=/app/huggingface_cache
    depends_on:
      - postgres
      - chromadb
      - llama
    volumes:
      - ./src/fastapi/pyproject.toml:/app/pyproject.toml
      - ./src/fastapi/poetry.lock:/app/poetry.lock
      - ./data/huggingface_cache:/app/huggingface_cache
    networks:
      - rag_net
  streamlit:
    build:
      context: .
      dockerfile: src/streamlit_app/Dockerfile.streamlit
      args:
        HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    env_file:
      - .env
    environment:
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_API_KEY}
      - STREAMLIT_WATCH_FILES=false
    volumes:
      - ./src/streamlit_app/pyproject.toml:/app/pyproject.toml
      - ./src/streamlit_app/poetry.lock:/app/poetry.lock
    networks:
      - rag_net

networks:
  rag_net:
    driver: bridge